#+TITLE: Helm-Recoll

[[https://github.com/emacs-helm/helm-recoll/blob/master/LICENSE][file:http://img.shields.io/badge/license-GNU%20GPLv3-blue.svg]]
[[http://stable.melpa.org/#/helm-recoll][file:http://stable.melpa.org/packages/helm-recoll-badge.svg]]
[[http://melpa.org/#/helm-recoll][file:http://melpa.org/packages/helm-recoll-badge.svg]]

Helm interface for the recoll desktop search tool.

* Table of contents

 - [[#commentary][Commentary]]
 - [[#installation][Installation]]
 - [[#license][License]]

* Commentary

You need to create some =helm-recoll= sources before you can use them.
You can create sources using the =helm-recoll-create-source= macro,
e.g. like this:

#+begin_src emacs-lisp
  (helm-recoll-create-source "docs" "~/.recoll/docs")
  (helm-recoll-create-source "progs" "~/.recoll/progs")
#+end_src

=helm-recoll-create-source= defines a source named
=helm-source-recoll-NAME= and an individual command named
=helm-recoll-NAME= for every defined source.  With the above
definitions, the commands =helm-recoll-docs= and =helm-recoll-progs=
would be provided and start a Helm session for the created
=helm-source-recoll-docs= and =helm-source-recoll-progs= sources
respectivly.

In addition, the command =helm-recoll= lists all currently defined
recoll sources, and starts a helm session running the selected ones.

* Installation

Add a require statement for the library:

#+begin_src emacs-lisp
  (require 'helm-recoll)
#+end_src

to your init file (typically ~/.emacs) and add your source definitions
like shown above.

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
